var vars = require('./vars'),
	gulp = require('gulp'),
	duplicate = require('gulp-rename'),
	gzip = require('gulp-gzip'),
	localServer = require('gulp-connect'),
	concat = require('gulp-concat'),
	uglifyJs = require('gulp-uglify'),
	checkJs = require('gulp-jshint'),
	modernizer = require('gulp-modernizr');

gulp.task('process-scripts', function() {
	return gulp.src([
		vars.paths.scripts.src + 'app.js',
		vars.paths.scripts.src + 'controllers/index.js',
		vars.paths.scripts.src + 'controllers/*.js',
		vars.paths.scripts.src + 'services/index.js',
		vars.paths.scripts.src + 'services/*.js',
		vars.paths.scripts.src + 'directives/index.js',
		vars.paths.scripts.src + 'directives/*.js',
		vars.paths.scripts.src + 'filters/index.js',
		vars.paths.scripts.src + 'filters/*.js',
		vars.paths.scripts.src + 'animation/index.js',
		vars.paths.scripts.src + 'animation/*.js'
	])
	.pipe(concat(vars.renderedNames.javascript.myJs))
	.pipe(checkJs())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(duplicate({suffix: '.min'}))
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(gzip())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(localServer.reload());
});

gulp.task('modernize', function() {
	return gulp.src(vars.watchedJsFiles)
	.pipe(modernizer())
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.src + 'autogenerated/'));
});
