var src = 'src',
	dest = 'dest';

var paths = {
	html: {
		src: src + '/**/*.html',
		dest: dest + '/'
	},
	styles: {
        src: src + '/styles/**/*.+(scss|sass)',
        dest: dest + '/styles/'
    },
    scripts: {
        src: src + '/scripts/',
        dest: dest + '/scripts/'
    },
    json: {
        src: src + '/data/**/*.json',
        dest: dest + '/data/'
    },
    images: {
        src: src + '/data/images/**/*',
        dest: dest + '/data/images/'
    },
    fonts: {
        src: 'bower_components/**/*.+(eot|ttf|woff|woff2)',
        dest: dest + '/styles/fonts/'
    },
    bower: 'bower_components/',
    deploy: './' + dest + '/**/*',
};

var jsLibraries = {
	angular: {
        min: paths.bower + 'angular/angular.min.js',
        debug: paths.bower + 'angular/angular.js'
    },
    angularRoute: {
        min: paths.bower + 'angular-route/angular-route.min.js',
        debug: paths.bower + 'angular-route/angular-route.js'
    },
    angularResource: {
        min: paths.bower + 'angular-resource/angular-resource.min.js',
        debug: paths.bower + 'angular-resource/angular-resource.js'
    },
    angularSanitize: {
        min: paths.bower + 'angular-sanitize/angular-sanitize.min.js',
        debug: paths.bower + 'angular-sanitize/angular-sanitize.js'
    },
    angularAnimate: {
        min: paths.bower + 'angular-animate/angular-animate.min.js',
        debug: paths.bower + 'angular-animate/angular-animate.js'
    },
};

var renderedNames = {
	javascript: {
		myJs: 'my-scripts.js',
		debug: 'libraries-debug.js',
		min: 'libraries.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.src + '**/*.js'];

module.exports = {
    paths: paths,
    jsLibraries: jsLibraries,
    ignoreModernizr: ignoreModernizr,
    watchedJsFiles: watchedJsFiles,
    renderedNames: renderedNames,
};